version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    command: ./start.sh
    depends_on:
      - db

  db:
    container_name: comerc_mysql
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: comerc
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql_password

  s3:
    build:
      context: docker/s3
    ports:
      - "9444:9000"

volumes:
  mysql-data:
  localstack:
    driver: local
