version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    container_name: comerc_mysql
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_password
      MYSQL_DATABASE: comerc
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql_password

  localstack:
    image: localstack/localstack:latest
    container_name: travel_moon_localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
    volumes:
      - "localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mysql-data:
  localstack:
    driver: local
